# Generated by Django 5.1 on 2024-10-02 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LeaveApp", "0002_rename_attachment_attachments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attachments",
            new_name="Attachment",
        ),
    ]
