# Generated by Django 5.1 on 2024-09-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("Absent", "Absent"), ("Present", "Present")],
                default="Absent",
                max_length=20,
            ),
        ),
    ]
