# Generated by Django 5.1 on 2024-09-20 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_alter_attendance_date_alter_attendance_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="date",
            new_name="timestamp",
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="time",
        ),
    ]
